### ISSUE TITLE
访问js、css文件永远是200返回

### ISSUE THREAD

**Issue by FlodCoding** [yale8848/CacheWebView#65]
测试时发现If-Modified-Since:Last-Modified和If-None-Match:ETag同时使用去请求js、css文件时（文件未修改），会返回200，同样只添加If-None-Match:ETag也是返回200，但是只添加If-Modified-Since:Last-Modified时才会返回304。这样js、css文件一直不会被缓存。不知其中的原因。。。。

**Comment by yale8848** [comment]
1.请提供详细的测试用例；
2.设置强制缓存了吗？WebViewCache.CacheStrategy.FORCE

**Comment by FloodComing** [comment]
1、缓存策略是nomal
2、http://101.200.149.181:8080/static/compass/stylesheets/screen-mobile.css

![_20180523100719](https://user-images.githubusercontent.com/33310779/40399645-1b85b0fe-5e71-11e8-8352-e48d3aa72645.png)
 今天发现服务器返回的Etag会在末尾带上-gzip，如果去掉-gzip去请求，就会返回304。似乎是服务器一种压缩策略自动加上了这个后缀

**Comment by yale8848** [comment]
我刚用chrome测试http://101.200.149.181:8080/static/compass/stylesheets/screen-mobile.css：

Request Header：

> Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Cache-Control: max-age=0
Connection: keep-alive
Cookie: csrftoken=jsssXiDyqNui5TJoxl1P9N4RhkbrejuSxXJenWhWQjoAHBbEEHBtroxXHRUJ4QQe; sessionid=g6klpu0rmlm8j9r8mc31o4l2mssf7ktr
Host: 101.200.149.181:8080
If-Modified-Since: Mon, 21 May 2018 08:08:22 GMT
If-None-Match: "79c66-56cb2ce2d6c60-gzip"
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

Response Header:

> Accept-Ranges: bytes
Connection: Keep-Alive
Content-Encoding: gzip
Content-Length: 57766
Content-Type: text/css
Date: Wed, 23 May 2018 02:17:14 GMT
ETag: "79c66-56cb2ce2d6c60-gzip"
Keep-Alive: timeout=5, max=100
Last-Modified: Mon, 21 May 2018 08:08:22 GMT
Server: Apache/2.4.7 (Ubuntu)
Vary: Accept-Encoding

> Status Code: 200 OK

连续请求几次都是200

我这测试如果Request Header只有：If-Modified-Since: Mon, 21 May 2018 08:08:22 GMT，那么服务器端返回304正常；

关于ETag的-gzip:

如果Request Header添加：Accept-Encoding: gzip, deflate，那么ETag返回添加-gzip,79c66-56cb2ce2d6c60-gzip，如果给header里添加此ETag，返回200；

如果Request  header里不加gzip，ETag返回正常，再次请求正常304；

综上所述：

这个链接如果Request Header添加：Content-Encoding: gzip ，那么永远返回200；

同时服务器判断规则是ETag优先Last-Modified；

错误原因：
`Request Header 有 Accept-Encoding: gzip，ETag有-gzip，但是服务端判断时没有对gzip做处理，判断有误，不能匹配，忽略Last-Modified，返回200`

请和服务端确认一下是不是这样的？

**Comment by FloodComing** [comment]
服务端那边确实未作处理，所以响应头Etag会默认带上“-gzip”，Thinks
